version: '3.9'

networks:
  product_service_network:

services:
  product_service:
    build:
      context: ./product_service
    networks:
      product_service_network:
    volumes:
      - ./product_service/:/app
      - static_volume:/app/static
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - ./product_service/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    networks:
      product_service_network:
    restart: always
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./product_service/.env
    ports:
      - "5432-5432"

  nginx:
    image: nginx:latest
    networks:
      product_service_network:
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - product_service

  redis:
    image: redis:latest
    networks:
      product_service_network:
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./product_service
    networks:
      product_service_network:
    command: celery -A product_service worker -l info
    volumes:
      - ./product_service:/app
    env_file:
      - ./product_service/.env
    depends_on:
      - redis
      - db


volumes:
  postgres_volume:
  static_volume:




