version: '3.9'

services:
  product_service:
    build:
      context: ./product_service
    volumes:
      - ./product_service/:/app
      - static_volume:/app/static
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - ./product_service/.env
    depends_on:
      - db


  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespostgres
    ports:
      - "5432-5432"




  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - product_service


#    networks:
#      - prediction-network
#    depends_on:
#      - prediction-app
#      - prediction


volumes:
  postgres_volume:
  static_volume:




